lib: [
  "_build/install/default/lib/Game/META"
  "_build/install/default/lib/Game/dune-package"
  "_build/install/default/lib/Game/game.a"
  "_build/install/default/lib/Game/game.cma"
  "_build/install/default/lib/Game/game.cmi"
  "_build/install/default/lib/Game/game.cmt"
  "_build/install/default/lib/Game/game.cmx"
  "_build/install/default/lib/Game/game.cmxa"
  "_build/install/default/lib/Game/game.ml"
  "_build/install/default/lib/Game/game__Start.cmi"
  "_build/install/default/lib/Game/game__Start.cmt"
  "_build/install/default/lib/Game/game__Start.cmx"
  "_build/install/default/lib/Game/opam"
  "_build/install/default/lib/Game/start.ml"
]
libexec: [
  "_build/install/default/lib/Game/game.cmxs"
]
